; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
lib_ldf_mode = chain+
lib_compat_mode = strict
build_flags =
  -std=gnu++2a
  -Wall
  -fno-exceptions
  -D RGB_ARDUINO
  -D RGB_ARDUINO_NANO
  -D RGB_VEHICLE_CORE_STACK_SIZE=8192
  -D RGB_VEHICLE_CORE_PRIORITY=1
  -D RGB_VEHICLE_CORE_DISABLE=0
  -I"src/car"
  -I"src/core"
  -I"src/core/debug"
  -I"src/core/event"
  -I"src/core/led"
  -I"src/core/network"
  -I"src/core/pixel"
  -I"src/core/priv"
  -I"src/core/sensor"
  -I"src/core/threading"
  -I"src/core/time"
  -I"src/effect"
  -I"src/main"
  -I"src/rgb"
build_unflags =
  -std=gnu++11
  -fexceptions
lib_deps=
  ESP32Async/ESPAsyncWebServer
  olikraus/U8g2
  adafruit/Adafruit NeoPixel
  z3t0/IRremote@4.4.2
  adafruit/Adafruit BusIO
  fastled/FastLED

[env:verbose]
build_flags =
  ${env.build_flags}
  -D RGB_DEBUG
  -D RGB_LOG_LEVEL=2
  '-D RGB_WIFI_SSID="The Big Enchilada"'
  !echo '-D RGB_WIFI_PASSWORD=\\"'$(echo $RGB_WIFI_PASSWORD)'\\"'

[env:debug]
build_flags =
  ${env.build_flags}
  -D RGB_DEBUG
  '-D RGB_WIFI_SSID="The Big Enchilada"'
  !echo '-D RGB_WIFI_PASSWORD=\\"'$(echo $RGB_WIFI_PASSWORD)'\\"'

[env:release]
build_flags =
  ${env.build_flags}
  '-D RGB_WIFI_SSID="The Big Enchilada"'
  !echo '-D RGB_WIFI_PASSWORD=\\"'$(echo $RGB_WIFI_PASSWORD)'\\"'

[env:ci]
build_flags =
  ${env.build_flags}