resources:
  - name: repo
    type: git
    source:
      uri: ((git.uri))
      branch: master
      private_key: ((git.private-key))

jobs:     
  - name: build-library
    public: true
    plan:
      - get: repo
        trigger: true
      - task: build-library
        file: repo/cicd/tasks/build.yml