resources:
  - name: repo
    type: git
    source:
      uri: ((git.uri))
      branch: master
      private_key: ((git.private-key))

jobs:     
  - name: build-library
    public: true
    plan:
      - get: repo
        trigger: true
      - task: build-library
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          inputs:
            - name: repo
          run:
            path: ls
            args: [ "repo/cicd" ]