resources:
  - name: rgblib
    type: git
    source:
      uri: ((git.uri))
      branch: master
      private_key: ((git.private-key))
      commit_filter:
        exclude: [ "UpdateVersion" ]

  - name: version
    type: git
    source:
      uri: ((git.uri))
      branch: master
      private_key: ((git.private-key))

jobs:     
  - name: build
    public: true
    plan:
      - get: rgblib
        trigger: true
      - task: build
        timeout: 10m
        file: rgblib/cicd/tasks/build.yml
  - name: deploy
    public: true
    plan:
      - get: rgblib
        trigger: true
        passed: [ build ]
      - get: version
        passed: [ build ]
      - task: deploy
        timeout: 10m
        params:
          PIO_USERNAME: ((pio.username))
          PIO_PASSWORD: ((pio.password))
        file: rgblib/cicd/tasks/deploy.yml
      - put: version
        params:
          repository: version