resources:
  - name: repo
    type: git
    source:
      uri: ((git.uri))
      branch: master
      private_key: ((git.private-key))
#      commit_filter:
#        exclude: [ "\\[Version]\\" ]

jobs:     
  - name: build-library
    public: true
    plan:
      - get: repo
        trigger: true
      - task: build-library
        params:
          PIO_USERNAME: ((pio.username))
          PIO_PASSWORD: ((pio.password))
        file: repo/cicd/tasks/build.yml
      - put: repo
        params:
          repository: repo