resources:
  - name: repo
    type: git
    source:
      uri: ((git.uri))
      branch: master
      private_key: ((git.private-key))
      commit_filter:
        exclude: [ "UpdateVersion" ]

jobs:     
  - name: build
    public: true
    plan:
      - get: repo
        trigger: true
      - task: build
        timeout: 10m
        file: repo/cicd/tasks/build.yml
  - name: deploy
    public: true
    plan:
      - get: repo
        trigger: true
        passed: [ build ]
      - task: deploy
        timeout: 10m
        params:
          PIO_USERNAME: ((pio.username))
          PIO_PASSWORD: ((pio.password))
        file: repo/cicd/tasks/deploy.yml
      - put: repo
        params:
          repository: repo