platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
inputs:
  - name: repo
outputs:
  - name: repo
params:
  PIO_USERNAME: ((pio.username))
  PIO_PASSWORD: ((pio.password))
run:
  path: repo/cicd/tasks/build.sh