platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
inputs:
  - name: rgblib
  - name: version
outputs:
  - name: version
params:
  PIO_USERNAME: ((pio.username))
  PIO_PASSWORD: ((pio.password))
run:
  path: rgblib/cicd/tasks/deploy.sh